version: '3.8'

networks:
  mysql-network:
    name: mysql-network
    external: true

services:
 web-server:
  container_name: web-server
  build:
   context: .
  ports:
   - 80:80
  networks:
    - mysql-network